import logging
import json

from analyzer import Analyzer

queries = ["Free Cone Day from Daily Queen Holding",
			"Left Handed People Die Younger Than Right Handed People",
			"Betsy Devos say history textbook should be based on bible",
			"Paracetamol contaminated with a dangerous virus",
			"Tommy Chong Death",
			"Jokowi is chinese",
			"Jokowi is christian",
			"Airport scanners rip apart DNA",
			"Reginald VelJohnson Death",
			"Jokowi is the Indonesia president",
			"King Salman visit Bali",
			"Eat mince pies on Christmas Day in UK illegal",
			"Cherophobia is the fear of fun",
			"When hippos are upset, their sweat turns red",
			"Bananas are curved because they grow towards the sun.",
			"A lion's roar can be heard from 5 miles away!",
			"Facebook, Skype and Twitter are all banned in China.",
			"A baby octopus is about the size of a flea when it is born",
			"Japanese invaded and occupied Indonesia 1942",
			"Soekarno is the first president of Indonesia",
			"George Bush Death",
			"Japanese citizens is illegal to overweight",
			"The Komodo dragon is the largest lizard in the world",
			"Suharto was the most corrupt leader of all time",
			"Indonesia largest moslem population",
			"Indonesia is largest archipelago",
			"Borobudur temple in Central Java",
			"Indonesia and Monaco have the same flag",
			"Evolution fresh drinks poison",
			"Sherry Shepperd Die",
			"Charles Manson Death",
			"Eric Braverman",
			"Stevie Wonder was killed in a car crash",
			"Big Show was killed in a car accident",
			"Zsa Zsa Gabor Dies in 99",
			"Nutella Burger Mc'Donalds",
			"KFC create a chickhen-scented candle",
			"Giant squid found in New Zealand",
			"George Soros Dies of Heart Attack",
			"Harambe received 15,000 votes in the 2016 US Election",
			"clocks Pulp Fiction 4:20",
			"Forbes 2011 McDuck $44 billion",
			"Nelson Mandela Death",
			"Betty White Death",
			"Joyce Meyer Died 73 October 2016",
			"Montreal's city council ban pit bulls",
			"Miss Universe Alicia Machado Porn Star",
			"Brad Pitt Death",
			"Jellyfish 95 percent water",
			"Egplant-flavored condom durex",
			"Elvis Presley got a 'C' in his 8th grade music class",
			"Rowan Atkinson Death",
			"Younger brother kill big brother pokemon go",
			"Nicolas Cage Death",
			"John Cena Death",
			"Richard Harrison Death",
			"Author Cormac McCarthy passed away in June 2016",
			"Free concert tickets ticketmaster",
			"Actor Ralph Macchio of 'Karate Kid' fame passed away in June 2016",
			"Actor Jack Black passed away in June 2016",
			"WhatsApp Gold premium service",
			"Yosemite Sam banned by television",
			"Matthew Mccogney is Interstellar actor",
			"King Jong Nam killed in Malaysia",
			"Marvel Comics writer Stan Lee passed away in May 2016",
			"Americans are immune to the Zika virus",
			"Mark Zuckerberg Harvard dropped out",
			"Steve Jobs Death",
			"iphone 7 with no jack",
			"Google HTC made pixel phone",
			"Obama is the first dark skinned American President",
			"Wayne Rooney play for Manchester United",
			"Lionel Messi got ballon the or",
			"Habibie wife is Ainun",
			"Tokodai University in Japan",
			"HK UST in Hongkong",
			"Actor Anthony Hopkins has died"]

for query in queries:
	analyzer = Analyzer(query)
	result = analyzer.do()
	print(result["scores"])
	print(result["conclusion"])
